version: 2

models:
  - name: stg_customers
    description: "Cleaned customer records loaded from CSV seed data."
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_email
        tests:
          - not_null
  - name: stg_orders
    description: "Normalized order records with typed fields."
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_amount
        tests:
          - not_null